id: P010763
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16555
  title: བོན་གྱི་ལོ་རྒྱུས་ཡིག་ཆ་ཕྱོགས་སྒྲིག
  author: ''
  volumes:
    27ee5c73d1c54531ac4db46432a4cc66:
      image_group_id: I2PD18269
      title: ''
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
